### ISSUE TITLE
Неправильна тінь

### ISSUE THREAD

**Issue by a-vasyliev** [mallhate/clock_img_maker#2]
![beatles 9](https://user-images.githubusercontent.com/1255946/46261390-8317a380-c4fb-11e8-8838-1e3c6885c939.png)
![5-beatles 9](https://user-images.githubusercontent.com/1255946/46261391-89a61b00-c4fb-11e8-89d0-d67e26ded927.jpg)

**Comment by mallhate** [comment]
В дизайні обрізані пусті місця, які були необхідні для центрування з текстурою.

**Comment by a-vasyliev** [comment]
Тут не зовсім розумію. Типу маска завелика? Ок, тоді просто ресайзни маску перед її використанням до розміру текстури. Можеш розраховувати, що текстура протрімлена і немає відступів від країв.

**Comment by mallhate** [comment]
Ні, не завелика. В цьому випадку дизайна логічний центр зміщений вліво і в верх. Дизайн і текстура і так приводяться до одного розміру і далі іде обрізання текстури. Тобто після ресайзу виходить, що дизайн буде вде не в тих пропорціях і окрім цього,логічний центр

**Comment by mallhate** [comment]
![2](https://user-images.githubusercontent.com/43306498/46328270-070e8000-c60f-11e8-89b2-52ba416d2db9.png)
ось приклад після приведення до одного розміру

**Comment by mallhate** [comment]
![3](https://user-images.githubusercontent.com/43306498/46328407-b0ee0c80-c60f-11e8-8f9f-da18a1ef7f9c.JPG)
видно, що в дизайні обрізані краї. А правильно співставити такі картинки може тільки людина

**Comment by mallhate** [comment]
в останньому коміті тінь точно не буде виходити за текстуру, але текструра всеодно буде порізана не приавильно.
