### ISSUE TITLE
Моя помилка: забув попросити групувати по назві дизайну

### ISSUE THREAD

**Issue by a-vasyliev** [mallhate/clock_img_maker#3]
Зараз воно складає все згідно структури в сорс, я тупанув. Треба відобразити структуру з сорс, але ще й згрупувати по назві дизайну. Типу, якщо в папці сорс є таке: designs/music/beatles.png, то потрібно в результати скласти results/music/beatles/bg_name-design_name.jpg

Вибач, я не врахував це.

**Comment by mallhate** [comment]
зробив. тепер буде шлях:

> results/music/_beatles.png_/bg_name-design_name.jpg
