### ISSUE TITLE
Годинник неправильної форми

### ISSUE THREAD

**Issue by a-vasyliev** [mallhate/clock_img_maker#4]
![furious](https://user-images.githubusercontent.com/1255946/46317452-b16cb000-c5db-11e8-8dc9-ff3361d7a768.png)

![1-furious](https://user-images.githubusercontent.com/1255946/46317464-bb8eae80-c5db-11e8-8d96-1bc71469dc22.jpg)

**Comment by mallhate** [comment]
Цей баг відносить до теми "Неправильна тінь" https://github.com/mallhate/clock_img_maker/issues/2
в дизайні не вистачає зверху пустого місця.
