### ISSUE TITLE
Обробка дизайнів в порядку сортування по назві дизайну

### ISSUE THREAD

**Issue by a-vasyliev** [mallhate/clock_img_maker#6]

**Comment by mallhate** [comment]
Тобто всі бекграудли дизайну а.png потім всі b.png? А що робити з підпапками? В кожній підпапці своє сортування чи загальне для всіх файлів?

**Comment by a-vasyliev** [comment]
Ні, з бекграундами так як є дуже зручно. Треба вичитати всі назви дизайнів і тоді посортувати їх. Таким чином буде бекграунд 1 + дизайн по алфавіту, потім бекграунд 1 + наступний диз. по алфавіту

**Comment by a-vasyliev** [comment]
Працює, дякую!
